apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-initiate-reporting-jobs
spec:
  params:
    - name: username
    - name: password
    - name: url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: initiate-reporting-jobs-
      spec:
        pipelineRef:
            name: pipeline-initiate-reporting-jobs
        params:
          - name: username
            value: $(params.username)
          - name: password
            value: $(params.password)
          - name: url
            value: $(params.url)
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener-initiate-reporting-jobs
spec:
  triggers:
    - binding:
        name: trigger-initiate-reporting-jobs
      template:
        name: template-initiate-reporting-jobs