apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-initiate-reporting-jobs
spec:
  params:
    - name: username
    - name: password
    - name: url
  tasks:
    - name: task-initiate-reporting-jobs
      taskRef:
        name: task-initiate-reporting-jobs
      params:
        - name: username
          value: $(params.username)
        - name: password
          value: $(params.password)
        - name: url
          value: $(params.url)