apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-initiate-reporting-jobs
spec:
  workspaces:
    - name: pipeline-pvc
      mountPath: /pipeline-pvc
  params:
    - name: username
    - name: password
  steps:
    - name: initiate-reporting-jobs
      image: ibmcom/pipeline-base-image
      workingDir: /workspace
      env:
        - name: USERNAME
          value: $(params.username)
        - name: PASSWORD
          value: $(params.password)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -eo pipefail
          echo $USERNAME