apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-initiate-reporting-jobs
spec:
  params:
    - name: cdBrokerVaultPasswordConfigured
      default: 'false'
    - name: username
    - name: password
    - name: url
  steps:
    - name: initiate-reporting-jobs
      image: ibmcom/otc-deliver-base
      workingDir: /workspace
      env:
        - name: CD_BROKER_VAULT_PASSWORD_CONFIGURED
          value: $(params.cdBrokerVaultPasswordConfigured)
        - name: JOBS_USERNAME
          value: $(params.username)
        - name: JOBS_PASSWORD
          value: $(params.password)
        - name: JOBS_URL
          value: $(params.url)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -eo pipefail
          if [[ $CD_BROKER_VAULT_PASSWORD_CONFIGURED ]]; then
            JOBS_PASSWORD=`echo "$JOBS_PASSWORD" | jq -r ".$JOBS_USERNAME"`
          fi
          curl -fi --request POST "$JOBS_URL" --header "Authorization: Basic $(echo -n "$JOBS_USERNAME:$JOBS_PASSWORD" | base64 -w 0)" 