apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-initiate-reporting-jobs
spec:
  workspaces:
    - name: pipeline-pvc
      mountPath: /pipeline-pvc
  params:
    - name: username
    - name: password
    - name: url
  steps:
    - name: initiate-reporting-jobs
      image: ibmcom/otc-deliver-base
      workingDir: /workspace
      env:
        - name: JOBS_USERNAME
          value: $(params.username)
        - name: JOBS_PASSWORD
          value: $(params.password)
        - name: JOBS_URLs
          value: $(params.url)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -eo pipefail
          curl --request POST "$JOBS_URL" --header "Authorization: Basic $(echo -n "$JOBS_USERNAME:$JOBS_PASSWORD" | base64)"